name: Test against RabbitMQ stable (PR)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Checkout tls-gen
        uses: actions/checkout@v4
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
      - name: Test (no dynamic-batch publishing)
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Drabbitmq.stream.producer.dynamic.batch=false \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dclient.key=./tls-gen/basic/result/client_$(hostname)_key.pem
      - name: Test (dynamic-batch publishing)
        run: |
          ./mvnw test -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Drabbitmq.stream.producer.dynamic.batch=true \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dclient.key=./tls-gen/basic/result/client_$(hostname)_key.pem
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
      - name: Start cluster
        run: ci/start-cluster.sh
      - name: Test against cluster
        run: ./mvnw test -Dtest="*ClusterTest" -Drabbitmqctl.bin=DOCKER:rabbitmq0
      - name: Stop cluster
        run: docker compose --file ci/cluster/docker-compose.yml down
