name: Test against 3.11 stable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    services:
      rabbitmq:
        image: rabbitmq:3.11
        env:
          RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
        ports:
          - 5552:5552
          - 5672:5672
          - 1883:1883
          - 61613:61613

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Enable Stream, MQTT and STOMP plugins
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmq-plugins enable rabbitmq_stream rabbitmq_mqtt rabbitmq_stomp --offline
      - name: Stop RabbitMQ application
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmqctl stop_app
      - name: Start RabbitMQ application
        run: docker exec ${{job.services.rabbitmq.id}} rabbitmqctl start_app
      - name: Test
        run: ./mvnw test -Drabbitmqctl.bin=DOCKER:${{job.services.rabbitmq.id}}