name: Test against RabbitMQ alphas

on:
  schedule:
    - cron:  '0 4 * * *'
  push:
    branches:
      - main
    paths:
      - src/**
      - '!src/docs/**'
      - '!src/test/java/com/rabbitmq/stream/docs/*'
      - pom.xml
      - ci/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        rabbitmq-image:
          - pivotalrabbitmq/rabbitmq:v4.1.x-otp27
          - pivotalrabbitmq/rabbitmq:v4.2.x-otp27
    name:  Test against ${{ matrix.rabbitmq-image }}
    steps:
      - uses: actions/checkout@v5
      - name: Checkout tls-gen
        uses: actions/checkout@v5
        with:
          repository: rabbitmq/tls-gen
          path: './tls-gen'
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Start broker
        run: ci/start-broker.sh
        env:
          RABBITMQ_IMAGE: ${{ matrix.rabbitmq-image }}
      - name: Test (no dynamic-batch publishing)
        run: |
          ./mvnw verify -Drabbitmqctl.bin=DOCKER:rabbitmq \
            -Drabbitmq.stream.producer.dynamic.batch=false \
            -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
            -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
            -Dclient.key=./tls-gen/basic/result/client_$(hostname)_key.pem
      - name: Test (dynamic-batch publishing)
        run: |
          ./mvnw test -Drabbitmqctl.bin=DOCKER:rabbitmq \
          -Drabbitmq.stream.producer.dynamic.batch=true \
          -Dca.certificate=./tls-gen/basic/result/ca_certificate.pem \
          -Dclient.certificate=./tls-gen/basic/result/client_$(hostname)_certificate.pem \
          -Dclient.key=./tls-gen/basic/result/client_$(hostname)_key.pem
      - name: Stop broker
        run: docker stop rabbitmq && docker rm rabbitmq
      - name: Start cluster
        run: ci/start-cluster.sh
        env:
          RABBITMQ_IMAGE: ${{ matrix.rabbitmq-image }}
      - name: Test against cluster
        run: ./mvnw test -Dtest="*ClusterTest" -Drabbitmqctl.bin=DOCKER:rabbitmq0
      - name: Stop cluster
        run: docker compose --file ci/cluster/docker-compose.yml down
